### ISSUE TITLE
H5P-results from Essay not saved within Moodle

### ISSUE THREAD

**Issue by cljkoopman** [otacke/h5p-essay#17]
Hi,

Recently, the activity Essay was launched within H5P. Great! I also found a beta version of Dictation. Even greater!

But: the results that I score within both activities are not passed on to the Moodle grade list. That's less great.

Am I doing something wrong? Do I have to wait for an update of the H5P plug-in? Who knows the right answer?

Greeting, Kees Koopman.

**Comment by otacke** [comment]
As I said on the H5P Forum: I have not yet given attention to moodle specific requirements. I'll look into that. You should notice when the feature is implemented, because then I'll close this issue :-)

**Comment by otacke** [comment]
added functionality, but should be tested some more

**Comment by otacke** [comment]
Score is now saved in moodle gradebook. DONE.

**Comment by cljkoopman** [comment]
Great job!
Question: how do I get this update?

**Comment by otacke** [comment]
You just have to wait :-) As soon as someone from the core team gets around to it, it will be uploaded to the H5P Hub and you'll notice that a new version is available. If it's urgent, you could also build the new library version from the source code here, too.
