### ISSUE TITLE
Table with feedback for specific keywords should display actually found alternative

### ISSUE THREAD

**Issue by sr258** [otacke/h5p-essay#21]
It's excellent that you can specify feedback if a certain keyword was found or not. However, I'd like to propose a change about how the feedback is displayed: if the user enters a keyword from the alternatives list, the feedback table still displays the "main keyword". It would be better if the keyword in the table was the actually entered keyword. If the "main keyword" is displayed it might confuse the reader, as he/she didn't really enter it.

**Comment by otacke** [comment]
The previous behavior was implemented, but the beta testers prefered the "expected solution" version. I'll think about a switch in options -- don't want to bloat the editor though. Thanks for the suggestion!

**Comment by otacke** [comment]
done
