### ISSUE TITLE
Add capability for the teacher to view submitted essays

### ISSUE THREAD

**Issue by sr258** [otacke/h5p-essay#23]
This is mentioned in the readme already, but I think this is a high priority feature, so I repost it here to make it more visible:

It would be really useful if teachers could view the submitted essays in their LMS. So in Moodle the gradebook module would display the texts the student entered. There are several H5P module that already have this capability (e.g. Quiz with Multiple Choice).

**Comment by otacke** [comment]
This functionality has already been added. The latest version has not yet been uploaded to h5p.org though. Cmp.: [https://h5p.org/node/191810](https://h5p.org/node/191810).
