### ISSUE TITLE
xAPI for Essay

### ISSUE THREAD

**Issue by ischnee** [otacke/h5p-essay#33]
Hi, on h5p.org it lists no xAPI coverage for Essay, but reading around on comments it seems that some gradebooks like moodle are getting graded data. I'm using wordpress and it would be great to know if Essay can generate xAPI statements on correct answers. Sorry if the answer is out there and I haven't been able to turn it up yet. Thanks!

**Comment by otacke** [comment]
Hi ischnee!

It's the other way around: xAPI has been supported from the very beginning (despite not being listed on h5p.org, but gradebook support for host environments is not available yet. The code for that has been implemented quite some time ago, but the core team has not come around to review it.
