### ISSUE TITLE
H5P Essay question

### ISSUE THREAD

**Issue by GalvoJ** [otacke/h5p-essay#38]
Essay question currently allows the teacher to specify how many characters the learner can use in their response to the essay question, but the teacher is capped at 255 characters.
It would be extremely useful if the teacher can specify the length of the feedback as we often feel limited by the this character cap.

**Comment by otacke** [comment]
@GalvoJ 
The length of the feedback fields [has been increased to 1.000 characters](https://github.com/otacke/h5p-essay/blob/master/semantics.json#L189-L202) a year ago, but the H5P core team has not realeased this update yet.

**Comment by GalvoJ** [comment]
> @GalvoJ
> The length of the feedback fields [has been increased to 1.000 characters](https://github.com/otacke/h5p-essay/blob/master/semantics.json#L189-L202) a year ago, but the H5P core team has not realeased this update yet.

Do we have any time frame on when this might be released?

**Comment by otacke** [comment]
@GalvoJ 
You'd have to ask someone from the H5P core team, not me. The [ticket has been set to done](https://h5ptechnology.atlassian.net/browse/HFP-1879), so I assume it's going to be out soon.
