### ISSUE TITLE
A single `*` freezes the browser

### ISSUE THREAD

**Issue by iamCristYe** [otacke/h5p-essay#67]
As described in the hint:
`Keyword or phrase to look for. Use an asterisk '*' as a wildcard for one or more characters. Use a slash '/' at the beginning and the end to use a regular expression. `
I tried to use a single `*` to match all words (give full marks whenever there's input), and the browser is freezing. Currently I'm using `**` or`/.+/` as a fix.

I suspect the problematic code is located at
https://github.com/otacke/h5p-essay/blob/master/scripts/essay.js#L674
where `needle` is replaced to be ``, and then stuck in the loop on line 678.

**Comment by otacke** [comment]
@iamCristYe Thanks for reporting that! Easy fix, done. But I am curious about the use case for matching all words unconditionally? Is it really just giving full score for typing anything? You could also use the 'ignore scoring' setting in that case, as scoring a text merely based on keywords is kind of weird anyway.

**Comment by iamCristYe** [comment]
Yes, giving full score for typing anything :) I didn't notice ignore scoring before, let me check that. Thx anyway!

**Comment by otacke** [comment]
You're welcome! The H5P core team currently is too busy to take care of external contributions, so I'll ask them to release an update to the H5P Hub once they have finished work on the H5P OER Hub.
