### ISSUE TITLE
Pass 'i' flag to regex if !caseSensitive

### ISSUE THREAD

**Issue by mkpelletier** [otacke/h5p-essay#78]
This may be some low-hanging fruit that will greatly simplify regular expressions.  Rather than specify caseSensitive in the Regexp options, use the configuration settings.  This would allow users to make use of the i flag when writing their expressions.

**Comment by otacke** [comment]
Where do you think a call to https://github.com/otacke/h5p-essay/blob/master/scripts/essay.js#L899 is missing? Feel free to create a pull request.

**Comment by mkpelletier** [comment]
Ah, thanks... I missed that.  Is this live on h5p.com?  It doesn't seem to work there.  It is funny because I remember suggesting this patch several years ago.
