### ISSUE TITLE
essay.js fails to handle null previousState

### ISSUE THREAD

**Issue by nwp90** [otacke/h5p-essay#83]
When contentData is passed in with previousState == null, javascript error results ("Uncaught TypeError: can't convert null to object" at line 126 of essay.js in version 1.5.3) and content fails to display.

**Comment by otacke** [comment]
@nwp90 Thanks, fixed in https://github.com/otacke/h5p-essay/commit/cc6c3dd19223afdb2f42513a690036c860e898cf But how would the state ever be `null` in the first place?

**Comment by nwp90** [comment]
Seems to be somehow when Essay is used within Interactive Book...

**Comment by nwp90** [comment]
Are you likely to do a release soon or do I need to somehow zip this up and upload it locally (not sure how H5P deals with version numbers in that case - can I just upload it as 1.5.3 again?)

**Comment by otacke** [comment]
> Seems to be somehow when Essay is used within Interactive Book...

Ah, I see.

**Comment by otacke** [comment]
> Are you likely to do a release soon or do I need to somehow zip this up and upload it locally (not sure how H5P deals with version numbers in that case - can I just upload it as 1.5.3 again?)

I am not part of the H5P core team and cannot release anything to the H5P Hub. Most of my repositories contain versions of content types that are (way) more advanced than what you can find on the H5P Hub, but I cannot tell when those might be reviewed and released. Sometimes the process is quick, sometimes it takes months or longer.

If you want to patch things, you should clone the repository and [use the H5P CLI tool ](https://h5p.org/h5p-cli-guide) to build the H5P library. Mind versioning though (cmp. [tutorial by Peter Baumgartner](https://peter.baumgartner.name/2021/04/12/h5p-library-installation/) incl. my comments).

**Comment by nwp90** [comment]
Fantastic, thanks :)

**Comment by nwp90** [comment]
Confirmed this has fixed the problem. Thanks again :)

**Comment by otacke** [comment]
No problem, thanks for reporting.
