### ISSUE TITLE
How to upgrade h5p essay to the latest version of this repo in my Moodle?

### ISSUE THREAD

**Issue by fishfree** [otacke/h5p-essay#84]
In my Moodle, it's 1.2. So I don't know how to upgrade to 1.4 in this repo. Thank you very much!

**Comment by otacke** [comment]
Why do you want 1.4? That's an outdated version. As an admin you can update to the latest version normally by using the update function of the H5P Hub (if you're using the H5P plugin) or by using the cron job provided by moodle's custom H5P integration, or by uploading the demo content from https://h5p.org/content-types/essay

**Comment by fishfree** [comment]
@otacke Hi, otacke. The one in Moodle and in H5P is older than your released version in this Github repo.

**Comment by otacke** [comment]
@fishfree I don't know what you mean. The lattest version that you find here is labeled 1.5.3 and that is the same version label that H5P.org currently serves. As mentioned before, you can update your moodle platform by one of the methods described above.

**Comment by fishfree** [comment]
@otacke Thank you for your resisting repetition. Finally I found the new version of the plugin was restricted on the page /mod/hvp/library_list.php.
