### ISSUE TITLE
Using '\n' in the keyword doesn't behave as intended 

### ISSUE THREAD

**Issue by Multipixels** [otacke/h5p-essay#88]
https://h5p.org/node/1427613

I've been using H5P Essay to ask students for the output of a simple code block, but I've been struggling to get multiline input working correctly. I couldn't find a correct input when using \n for the question I linked above.

A correct answer should look like:

You got a B!
You got a C!
You got a D!

Using `/You got a B!\nYou got a C!\nYou got a D!/` as the keyword should match it, but it doesn't seem to.

I'm temporarily using \s to match any whitespace, and that seems to work for newlines too but it also accepts some undesired answers, like:

You got a B! You got a C! You got a D!

I presume this is a limitation with newlines being handled as spaces, but do let me know if there's an alternative solution that I'm missing. Thanks!

**Comment by otacke** [comment]
Line breaks are replaced by spaces, correct. And two spaces will be replaced by one. I don't think there's a workaround currently except for accepting `You got a B! You got a C! You got a D!` which would be beyond the point having a `print` exercise.

The respective replacement function has an argument for actual the line break replacement (falling back to ` `) already, but it's not used anywhere. Until now ...

I just added an option that allows to change the line break replacement to `\n` for cases like yours. Please note, however, that it's beyond my powers to update Essay on the H5P Hub. You'll have to request the H5P core team to retrieve the latest version of Essay (1.5.7) and use that.
